# Generated by Django 3.2.3 on 2021-06-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zodiac',
            fields=[
                ('sign', models.CharField(max_length=15)),
                ('value', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('wiki', models.CharField(max_length=100)),
                ('north', models.BooleanField(default=True)),
                ('zodiac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='need_this.zodiac')),
            ],
        ),
    ]
